spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/banking_prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  elasticsearch:
    uris: http://elasticsearch:9200
  redis:
    host: redis
    port: 6379

logging:
  level:
    root: WARN
    com.example.bankingapi: INFO