spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    com.example.bankingapi: DEBUG