spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: UTC

app:
  jwt:
    secret: "your-256-bit-secret"
    expiration-ms: 86400000 # 24 ????

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics